from fpdf import FPDF
from datetime import datetime

class PIDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(80)
        self.cell(30, 10, 'Medical Analysis Report', 0, 0, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb}', 0, 0, 'C')

    def chapter_title(self, label):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 6, label, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 5, body)
        self.ln()

    def add_section(self, title, body):
        if not body: return
        self.chapter_title(title)
        self.chapter_body(body)

class ReferralLetter(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 14)
        self.cell(0, 10, 'PATIENT REFERRAL SUMMARY', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by Medical AI Assistant (Screening Only)', 0, 0, 'C')

def create_pdf(data, filename):
    pdf = PIDFReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Summary
    pdf.add_section("Clinical Summary", data.get('summary', ''))
    
    # Risks
    if data.get('risks'):
        pdf.set_text_color(200, 0, 0)
        pdf.chapter_title("Risk Assessment")
        pdf.set_text_color(0, 0, 0)
        pdf.set_font('Arial', '', 11)
        for risk in data['risks']:
            pdf.cell(0, 6, f"- {risk.get('type')}: {risk.get('status')} ({risk.get('detail')})", 0, 1)
        pdf.ln()

    # Recommendations
    if data.get('recommendations'):
        pdf.chapter_title("Recommendations")
        pdf.set_font('Arial', '', 11)
        for rec in data['recommendations']:
            pdf.cell(0, 6, f"* {rec.get('action')}: {rec.get('advice')}", 0, 1)
        pdf.ln()

    # Labs (Table)
    if data.get('labs'):
        pdf.chapter_title("Key Laboratory Findings")
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(60, 7, 'Test', 1)
        pdf.cell(40, 7, 'Value', 1)
        pdf.cell(40, 7, 'Ref Range', 1)
        pdf.cell(40, 7, 'Status', 1)
        pdf.ln()
        
        pdf.set_font('Arial', '', 10)
        for lab in data['labs']:
            pdf.cell(60, 6, lab.get('name')[:30], 1)
            pdf.cell(40, 6, f"{lab.get('value')} {lab.get('unit')}", 1)
            pdf.cell(40, 6, lab.get('reference'), 1)
            
            # Highlight abnormal
            status = lab.get('status', 'Normal')
            if status != 'Normal':
                pdf.set_text_color(200, 0, 0)
            pdf.cell(40, 6, status, 1)
            pdf.set_text_color(0, 0, 0)
            pdf.ln()

    pdf.output(filename)
    return filename

def create_referral_letter(data, filename):
    """
    Generates a professional referral letter for a doctor.
    """
    pdf = ReferralLetter()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Date
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%B %d, %Y')}", 0, 1)
    pdf.ln(5)
    
    # Salutation
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 10, "To: Treating Physician / Specialist", 0, 1)
    pdf.cell(0, 10, "Re: Medical Report Finding Summary", 0, 1)
    pdf.ln(5)
    
    # Body
    pdf.set_font('Arial', '', 11)
    intro = (
        "Dear Provider,\n\n"
        "The patient has processed their medical records through an AI screening tool. "
        "The following summary highlights key findings, abnormalities, and potential risks "
        "extracted from the documents. This summary is intended to facilitate your review."
    )
    pdf.multi_cell(0, 6, intro)
    pdf.ln(5)
    
    # Findings Section
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "Key Clinical Findings", 0, 1)
    pdf.set_font('Arial', '', 11)
    
    # Add Visual Analysis result if relevant
    if data.get('report_type') == "Visual":
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(0, 8, "Imagining / Visual Analysis:", 0, 1)
        pdf.set_font('Arial', '', 11)
        pdf.multi_cell(0, 6, data.get('summary', ''))
        pdf.ln(2)
        
    # Add Text Analysis Summary
    if data.get('summary') and data.get('report_type') != "Visual":
        pdf.multi_cell(0, 6, data.get('summary', ''))
        pdf.ln(5)
        
    # Abnormalities List
    if data.get('risks'):
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(0, 10, "Identified Abnormalities / Risks:", 0, 1)
        pdf.set_font('Arial', '', 11)
        
        for risk in data['risks']:
            pdf.cell(0, 6, f"- {risk.get('detail')} ({risk.get('status')})", 0, 1)
        pdf.ln(5)
        
    # Closing
    pdf.set_font('Arial', 'I', 11)
    pdf.multi_cell(0, 6, "Thank you for reviewing this patient's case.")
    pdf.ln(10)
    
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 10, "__________________________", 0, 1)
    pdf.cell(0, 5, "Signature (System Generated)", 0, 1)
    
    pdf.output(filename)
    return filename
